### ISSUE TITLE
SIGSEGV: keys add mywallet --ledger

### ISSUE THREAD

**Issue by gaia** [akash-network/node#1746]
`akash keys add mywallet --ledger` yields one of the two error messages when run

`Error: failed to generate ledger key: failed to retrieve device: ledger nano S: couldn't find ledger device`
**OR**
```fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fb996ffe072 pc=0x7fb99c13ca7f]

runtime stack:
runtime.throw({0x21d8278?, 0x2a?})
	runtime/panic.go:1047 +0x5d fp=0x7fb996ffc768 sp=0x7fb996ffc738 pc=0x43bc3d
runtime.sigpanic()
	runtime/signal_unix.go:819 +0x369 fp=0x7fb996ffc7b8 sp=0x7fb996ffc768 pc=0x452669

goroutine 1 [syscall]:
runtime.cgocall(0x1c79410, 0xc000d9efe0)
	runtime/cgocall.go:158 +0x5c fp=0xc000d9efb8 sp=0xc000d9ef80 pc=0x405bbc
github.com/zondax/hid._Cfunc_hid_enumerate(0x0, 0x0)
	_cgo_gotypes.go:359 +0x4d fp=0xc000d9efe0 sp=0xc000d9efb8 pc=0xd72ecd
github.com/zondax/hid.Enumerate(0x3000?, 0x20?)
	github.com/zondax/hid@v0.9.0/hid_enabled.go:85 +0xd2 fp=0xc000d9f100 sp=0xc000d9efe0 pc=0xd737f2
github.com/zondax/ledger-go.(*LedgerAdminHID).CountDevices(0x1?)
	github.com/zondax/ledger-go@v0.12.2/ledger_hid.go:90 +0x2f fp=0xc000d9f200 sp=0xc000d9f100 pc=0xd7736f
github.com/cosmos/ledger-cosmos-go.FindLedgerCosmosUserApp()
	github.com/cosmos/ledger-cosmos-go@v0.11.1/user_app.go:61 +0x54 fp=0xc000d9f298 sp=0xc000d9f200 pc=0xd7a4b4
github.com/cosmos/cosmos-sdk/crypto/ledger.init.1.func1()
	github.com/cosmos/cosmos-sdk@v0.45.9/crypto/ledger/ledger_real.go:13 +0x17 fp=0xc000d9f2a8 sp=0xc000d9f298 pc=0xd7d4b7
github.com/cosmos/cosmos-sdk/crypto/ledger.getDevice()
	github.com/cosmos/cosmos-sdk@v0.45.9/crypto/ledger/ledger_secp256k1.go:187 +0x2a fp=0xc000d9f2e0 sp=0xc000d9f2a8 pc=0xd7ea4a
github.com/cosmos/cosmos-sdk/crypto/ledger.NewPrivKeySecp256k1({0x2c, 0x76, 0x0, 0x0, 0x0}, {0x217a52e, 0x5})
	github.com/cosmos/cosmos-sdk@v0.45.9/crypto/ledger/ledger_secp256k1.go:72 +0x85 fp=0xc000d9f3d8 sp=0xc000d9f2e0 pc=0xd7d8c5
github.com/cosmos/cosmos-sdk/crypto/keyring.keystore.SaveLedgerKey({{0x2b544c0, 0xc001236ba0}, {{0xc001257e70, 0x1, 0x1}, {0xc001257e80, 0x1, 0x1}}}, {0x7ffc2b642353, 0x8}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.9/crypto/keyring/keyring.go:392 +0x135 fp=0xc000d9f4f0 sp=0xc000d9f3d8 pc=0xd82f95
github.com/cosmos/cosmos-sdk/crypto/keyring.(*keystore).SaveLedgerKey(0xc0010c46f0?, {0x7ffc2b642353?, 0xc?}, {0x2b511e0?, 0x3c879a0?}, {0x217a52e?, 0x0?}, 0x0?, 0x0?, 0x0)
	<autogenerated>:1 +0x13f fp=0xc000d9f5d8 sp=0xc000d9f4f0 pc=0xd8b81f
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd({{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x2b57d10, 0xc00101be80}, {0x2b65fb8, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.9/client/keys/add.go:208 +0x62a fp=0xc000d9f788 sp=0xc000d9f5d8 pc=0x127776a
github.com/cosmos/cosmos-sdk/client/keys.runAddCmdPrepare(0xc00119c000?, {0xc00116c840, 0x1, 0x2})
	github.com/cosmos/cosmos-sdk@v0.45.9/client/keys/add.go:91 +0x29b fp=0xc000d9fd20 sp=0xc000d9f788 pc=0x12770db
github.com/spf13/cobra.(*Command).execute(0xc00119c000, {0xc00116c820, 0x2, 0x2})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694 fp=0xc000d9fdf8 sp=0xc000d9fd20 pc=0x5bb754
github.com/spf13/cobra.(*Command).ExecuteC(0xc00106ac80)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd fp=0xc000d9feb0 sp=0xc000d9fdf8 pc=0x5bbddd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.5.0/command.go:911
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0x0?, {0x2179ec6, 0x5})
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:100 +0x1f1 fp=0xc000d9ff58 sp=0xc000d9feb0 pc=0x1c6c5b1
main.main()
	github.com/ovrclk/akash/cmd/akash/main.go:15 +0x2a fp=0xc000d9ff80 sp=0xc000d9ff58 pc=0x1c6dfca
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc000d9ffe0 sp=0xc000d9ff80 pc=0x43e492
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000d9ffe8 sp=0xc000d9ffe0 pc=0x46ff81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00007cfb0 sp=0xc00007cf90 pc=0x43e856
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.forcegchelper()
	runtime/proc.go:302 +0xad fp=0xc00007cfe0 sp=0xc00007cfb0 pc=0x43e6ed
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00007cfe8 sp=0xc00007cfe0 pc=0x46ff81
created by runtime.init.6
	runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00007d790 sp=0xc00007d770 pc=0x43e856
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:297 +0xd7 fp=0xc00007d7c8 sp=0xc00007d790 pc=0x429017
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc00007d7e0 sp=0xc00007d7c8 pc=0x41dc86
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00007d7e8 sp=0xc00007d7e0 pc=0x46ff81
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000058070?, 0x2b2bad8?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00007df70 sp=0xc00007df50 pc=0x43e856
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.(*scavengerState).park(0x3c4fec0)
	runtime/mgcscavenge.go:389 +0x53 fp=0xc00007dfa0 sp=0xc00007df70 pc=0x427073
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:622 +0x65 fp=0xc00007dfc8 sp=0xc00007dfa0 pc=0x427665
runtime.gcenable.func2()
	runtime/mgc.go:179 +0x26 fp=0xc00007dfe0 sp=0xc00007dfc8 pc=0x41dc26
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x46ff81
created by runtime.gcenable
	runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x3c512e0?, 0xc0001024e0?, 0x0?, 0x0?, 0xc00007c770?)
	runtime/proc.go:363 +0xd6 fp=0xc00007c628 sp=0xc00007c608 pc=0x43e856
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.runfinq()
	runtime/mfinal.go:180 +0x10f fp=0xc00007c7e0 sp=0xc00007c628 pc=0x41cd8f
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00007c7e8 sp=0xc00007c7e0 pc=0x46ff81
created by runtime.createfing
	runtime/mfinal.go:157 +0x45

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000078750 sp=0xc000078730 pc=0x43e856
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0000787e0 sp=0xc000078750 pc=0x41fdd1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x46ff81
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x3ac21ec9adc?, 0x3?, 0xdb?, 0x4?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000078f50 sp=0xc000078f30 pc=0x43e856
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc000078fe0 sp=0xc000078f50 pc=0x41fdd1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x46ff81
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x3ac1cecd345?, 0x3?, 0x76?, 0xd4?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000079750 sp=0xc000079730 pc=0x43e856
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0000797e0 sp=0xc000079750 pc=0x41fdd1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000797e8 sp=0xc0000797e0 pc=0x46ff81
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x3ac21ee0f20?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000079f50 sp=0xc000079f30 pc=0x43e856
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc000079fe0 sp=0xc000079f50 pc=0x41fdd1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000079fe8 sp=0xc000079fe0 pc=0x46ff81
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 35 [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000137a80 sp=0xc000137a60 pc=0x43e856
runtime.netpollblock(0x0?, 0x0?, 0x0?)
	runtime/netpoll.go:526 +0xf7 fp=0xc000137ab8 sp=0xc000137a80 pc=0x4372d7
internal/poll.runtime_pollWait(0x7fb99c4d90c0, 0x72)
	runtime/netpoll.go:305 +0x89 fp=0xc000137ad8 sp=0xc000137ab8 pc=0x46a429
internal/poll.(*pollDesc).wait(0xc000540500?, 0xc00125ed60?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc000137b00 sp=0xc000137ad8 pc=0x4a76d2
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0xc000540500, {0xc00125ed60, 0x10, 0x10}, {0xc0004ee020, 0x1000, 0x1000}, 0x1?)
	internal/poll/fd_unix.go:304 +0x31c fp=0xc000137be0 sp=0xc000137b00 pc=0x4a9b7c
net.(*netFD).readMsg(0xc000540500, {0xc00125ed60?, 0x2b5abd0?, 0x1?}, {0xc0004ee020?, 0x0?, 0x96?}, 0x3bfc4f0?)
	net/fd_posix.go:78 +0x37 fp=0xc000137c68 sp=0xc000137be0 pc=0x53b957
net.(*UnixConn).readMsg(0xc0001201b8, {0xc00125ed60?, 0xc001079f38?, 0x2b31380?}, {0xc0004ee020?, 0x2b31380?, 0xc001237260?})
	net/unixsock_posix.go:115 +0x4f fp=0xc000137cf8 sp=0xc000137c68 pc=0x55d06f
net.(*UnixConn).ReadMsgUnix(0xc0001201b8, {0xc00125ed60?, 0xc000137df8?, 0x40f79f?}, {0xc0004ee020?, 0xc000137da0?, 0x43e940?})
	net/unixsock.go:143 +0x3c fp=0xc000137d70 sp=0xc000137cf8 pc=0x55b2dc
github.com/godbus/dbus.(*oobReader).Read(0xc0004ee000, {0xc00125ed60?, 0xc000137e20?, 0x40fae7?})
	github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/transport_unix.go:21 +0x45 fp=0xc000137de8 sp=0xc000137d70 pc=0xd572e5
io.ReadAtLeast({0x2b31f00, 0xc0004ee000}, {0xc00125ed60, 0x10, 0x10}, 0x10)
	io/io.go:332 +0x9a fp=0xc000137e30 sp=0xc000137de8 pc=0x4a217a
io.ReadFull(...)
	io/io.go:351
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc00012c330)
	github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/transport_unix.go:91 +0x11e fp=0xc000137f68 sp=0xc000137e30 pc=0xd578fe
github.com/godbus/dbus.(*Conn).inWorker(0xc00055a360)
	github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/conn.go:294 +0x3b fp=0xc000137fc8 sp=0xc000137f68 pc=0xd4043b
github.com/godbus/dbus.(*Conn).Auth.func1()
	github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/auth.go:118 +0x26 fp=0xc000137fe0 sp=0xc000137fc8 pc=0xd3d6e6
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000137fe8 sp=0xc000137fe0 pc=0x46ff81
created by github.com/godbus/dbus.(*Conn).Auth
	github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/auth.go:118 +0x9ee

goroutine 24 [chan receive]:
runtime.gopark(0xc000298008?, 0xc00052a4e0?, 0x20?, 0xef?, 0x45b6e5?)
	runtime/proc.go:363 +0xd6 fp=0xc000c9eec8 sp=0xc000c9eea8 pc=0x43e856
runtime.chanrecv(0xc0000a72c0, 0xc000c9efa0, 0x1)
	runtime/chan.go:583 +0x49b fp=0xc000c9ef58 sp=0xc000c9eec8 pc=0x408bbb
runtime.chanrecv2(0x12a05f200?, 0xd54cf7?)
	runtime/chan.go:447 +0x18 fp=0xc000c9ef80 sp=0xc000c9ef58 pc=0x4086f8
k8s.io/klog/v2.(*loggingT).flushDaemon(0xc000552c00?)
	k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x6a fp=0xc000c9efc8 sp=0xc000c9ef80 pc=0x1936e2a
k8s.io/klog/v2.init.0.func1()
	k8s.io/klog/v2@v2.30.0/klog.go:420 +0x26 fp=0xc000c9efe0 sp=0xc000c9efc8 pc=0x1934966
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000c9efe8 sp=0xc000c9efe0 pc=0x46ff81
created by k8s.io/klog/v2.init.0
	k8s.io/klog/v2@v2.30.0/klog.go:420 +0xf6

goroutine 23 [select]:
runtime.gopark(0xc000c9e7b0?, 0x2?, 0x0?, 0x30?, 0xc000c9e78c?)
	runtime/proc.go:363 +0xd6 fp=0xc000c9e600 sp=0xc000c9e5e0 pc=0x43e856
runtime.selectgo(0xc000c9e7b0, 0xc000c9e788, 0x14?, 0x0, 0xc000c9e7a0?, 0x1)
	runtime/select.go:328 +0x7bc fp=0xc000c9e740 sp=0xc000c9e600 pc=0x44e6dc
github.com/desertbit/timer.timerRoutine()
	github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:119 +0xba fp=0xc000c9e7e0 sp=0xc000c9e740 pc=0x1154f9a
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000c9e7e8 sp=0xc000c9e7e0 pc=0x46ff81
created by github.com/desertbit/timer.init.0
	github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:15 +0x25```
	
Same machine works fine with `regen keys add mywallet --ledger` (with the same ledger).

Akash v0.20.0, doesn't matter if it is compiled or binary. 
`build_tags: '"osusergo,netgo,ledger,static_build"'` (this is for the compiled version)

**Comment by gaia** [comment]
UPDATE: doesn't matter if the standalone binary is used, or built with the install script. Doesn't matter if it is 0.20 or 0.22
